export const SchoolPrograms = [
  {
    faculty: "Advanced School of Translators and Interpreters - ASTI",
    departments: [
      "Intercultural Studies - TIS",
      "GENERAL STUDIES AND PROMOTION OF BILINGUALISM - GS/PB",
      "INTERPRETATION - INT",
      "TRANSLATION - TRA",
    ],
  },
  {
    faculty: "College of Technology - COT",
    departments: [
      "COMPUTER ENGINEERING(COT) - CENG",
      "ELECTRICAL AND ELECTRONIC ENGINEERING(COT) - EENG",
      "MECHANICAL ENGINEERING - MET",
      "RECORDS - REC-COT",
      "RECORDS COT - RCT",
    ],
  },
  {
    faculty: "Faculty Agriculture and Veterinary Medicine - FAVM",
    departments: [
      "AGRICULTURAL ECONOMICS AND AGRIBUSINESS - AEA",
      "Agricultural Extension and Rural Development - AER",
      "AGRONOMIC AND APPLIED MOLECULAR SCIENCE - AAM",
      "ANIMAL SCIENCE - ANS",
      "Food Science and Technology - FSC",
      "Forestry and Wildlife - FWL",
      "Veterinary Medicine - DVM",
      "Fisheries and Aquatic Resources Management - FARM",
    ],
  },
  {
    faculty: "Faculty of Arts - FA",
    departments: [
      "Bilingual and Communication Studies - BCS",
      "ENGLISH - ENG",
      "HISTORY - HIS",
      "LINGUISTICS - LIN",
      "Performing and Visual Arts - PVA",
    ],
  },
  {
    faculty: "Faculty of Education - FED",
    departments: [
      "CURRICULUM STUDIES AND TEACHING - CST",
      "EDUCATIONAL FOUNDATIONS AND ADMINISTRATION - EFA",
      "EDUCATIONAL PSYCHOLOGY - EPY",
      "Library,Archival and Information Sciences - LSE",
      "RECORDS FED - REF",
    ],
  },
  {
    faculty: "Faculty of Engineering and Technology - FET",
    departments: [
      "Civil Engineering - CIV",
      "COMPUTER ENGINEERING(FET) - CEN",
      "Chemical and Petroleum Engineering - CPE",
      "ELECTRICAL AND ELECTRONIC ENGINEERING (FET) - EEN",
      "Mechanical and Industrial Engineering - MEF",
    ],
  },
  {
    faculty: "Faculty of Health Sciences - FHS",
    departments: [
      "Biomedical Sciences - BMS",
      "Obstetrics and Gynaecology - OBG",
      "MEDICAL LABORATORY SCIENCE - MLS",
      "MEDICINE - MED",
      "NURSING - NUR",
      "PUBLIC HEALTH AND HYGIENE - PHH",
      "RECORDS FHS - RECFHS",
      "Surgery and Specialities - SUS",
    ],
  },
  {
    faculty: "Faculty of Laws and Political Science - FLPS",
    departments: [
      "Business Law - BUL",
      "Civil Law - FLP",
      "English Law - LAW",
      "Political Science and Comparative Politics - POS",
      "Public Law and Public Administration - PUL-PUA",
      "Dept of International Relations and Conflict Resolutions - IRC",
    ],
  },
  {
    faculty: "Faculty of Science - FS",
    departments: [
      "ANIMAL BIOLOGY - ZAP",
      "BIOCHEMISTRY AND MOLECULAR BIOLOGY - BMB",
      "CHEMISTRY - CHM",
      "COMPUTER SCIENCE - CSC",
      "ENVIRONMENTAL SCIENCE - ENV",
      "GEOLOGY - GLY",
      "MATHEMATICS - MAT",
      "MICROBIOLOGY AND PARASITOLOGY - MBP",
      "PHYSICS - PHY",
      "PLANT SCIENCE - BPP",
      "RECORDS SCIENCE - RCS",
    ],
  },
  {
    faculty: "Faculty of Social and Management Sciences - FSMS",
    departments: [
      "BANKING AND FINANCE - BNF",
      "ECONOMICS AND MANAGEMENT - ECN",
      "GEOGRAPHY - GEO",
      "JOURNALISM AND MASS COMMUNICATION - JMC",
      "LAW - LAW",
      "MANAGEMENT - MGT",
      "POLITICAL SCIENCE - PSP",
      "RECORDS SMS - RECSMS",
      "SOCIOLOGY AND ANTHROPOLOGY - SOC/ANT",
      "WOMEN AND GENDER STUDIES - WGS",
    ],
  },
  {
    faculty: "Higher Technical Teachers Training College - HTTTC",
    departments: [
      "ADMINISTRATIVE TECHNIQUES - ADT",
      "AGRICULTURE - AGR",
      "CIVIL ENGINEERING & FORESTRY TECHNIQUES - CFT",
      "COMPUTER SCIENCE - CSCHT",
      "ELECTRICAL & POWER ENGINEERING - EPE",
      "GUIDANCE COUNSELING - GDC",
      "LAW - LAWHT",
      "MANAGEMENT SCIENCES - MGT",
      "MECHANICAL ENGINEERING - MEE",
      "RECORDS HTTTC - RHT",
      "RENEWABLE ENERGY - REN",
      "SCIENCE OF EDUCATION - SED",
      "SOCIAL ECONOMY & FAMILY MANAGEMENT - SEF",
      "TOPOGRAPHY & REAL ESTATE MANAGEMENT - TRE",
      "TOURISM & HOSPITALITY MANAGEMENT - THM",
    ],
  },
  {
    faculty: "System Management - SYM",
    departments: ["SYSTEM ADMINISTRATION - SYA"],
  },
];

export const Positions = [
  "PRESIDENT",
  "VICE PRESIDENT",
  "SECRETARY",
  "VICE SECRETARY",
  "PUBLIC RELATIONS OFFICER",
];
